### ISSUE TITLE
他说缺少这个类 咋回事，新手（我有这个包啊

### ISSUE THREAD

**Issue by eanson023** [liujingtech/IntelliJ-MySQL-Table-to-JPA-Entity#2]
`java.lang.NoClassDefFoundError: javax/persistence/GenerationType
	at org.liujing.generator.convert.java.MemberConvert.getAnnotationList(MemberConvert.java:61)
	at org.liujing.generator.convert.java.MemberConvert.convertMemberObject(MemberConvert.java:19)
	at org.liujing.generator.convert.java.ClassConvert.lambda$convertToClassObject$0(ClassConvert.java:28)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.liujing.generator.convert.java.ClassConvert.convertToClassObject(ClassConvert.java:27)
	at org.liujing.generator.FormatAction.actionPerformed(FormatAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:276)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:665)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:664)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javax.persistence.GenerationType PluginClassLoader[org.liujing.generator, 1.0.6] com.intellij.ide.plugins.cl.PluginClassLoader@3c2d13d1
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more`

**Comment by liujingtech** [comment]
让我看看你放到文本框内的建表sql,你还可以先试试说明文档内的标准sql,看是环境问题还是sql的问题

eanson <notifications@github.com> 于2020年3月1日周日 下午9:26写道：

**Comment by eanson023** [comment]
我就是用的文档的sql结果少包..

**Comment by liujingtech** [comment]
你的意思是你生成成功以后，代码界面上编译报错对吧。应该是你还没有开始导入jpa这个库。可以先学习一下：https://ityouknow.gitbooks.io/spring-data-jpa-reference-documentation/content/dependencies.html
